### ISSUE TITLE
Error with ReActions

### ISSUE THREAD

**Issue by OscarGLorenz** [FastFelix771/TownyWands#1]
Hello,

I have an error when using /vsign function. I am able to write the name of friend in the sign, but when I close it I am kicked from the server and I get this error:

[09:53:13] [Server thread/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[09:53:13] [Server thread/WARN]: [ProtocolLib] [ProtocolLibrary] Unable to send packet net.minecraft.server.v1_8_R3.PacketPlayOutChat@42d5d570 to ospa555
java.lang.NullPointerException: nmsPlayer cannot be null!
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:55) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:50) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.getPlayerConnection(NettyChannelInjector.java:740) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.invokeSendPacket(NettyChannelInjector.java:692) [ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$600(NettyChannelInjector.java:84) [ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$7.run(NettyChannelInjector.java:535) [ProtocolLib.jar:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
[09:53:13] [Server thread/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[09:53:13] [Server thread/WARN]: [ProtocolLib] [ProtocolLibrary] Unable to send packet net.minecraft.server.v1_8_R3.PacketPlayOutChat@6d519453 to ospa555
java.lang.NullPointerException: nmsPlayer cannot be null!
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:55) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:50) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.getPlayerConnection(NettyChannelInjector.java:740) ~[ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.invokeSendPacket(NettyChannelInjector.java:692) [ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$600(NettyChannelInjector.java:84) [ProtocolLib.jar:?]
    at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$7.run(NettyChannelInjector.java:535) [ProtocolLib.jar:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.jar:git-Spigot-0359393-9cd1111]

ProtocolLib is a plugin that is necessary for lots of plugins and a must have plugin in a server.

I'm using ProtocolLib 3.6.4 and "CraftBukkit version git-Spigot-0359393-9cd1111 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)"

**Comment by FastFelix771** [comment]
What's the command you are trying to execute with /vsign ?

**Comment by OscarGLorenz** [comment]
All commands, including your /resgui add friend, etc...

**Comment by FastFelix771** [comment]
I'll test the plugin with ProtocolLib, the technique behind the /vsign is a bit dirty :/

**Comment by FastFelix771** [comment]
I have tried it with the newest versions of Spigot, Towny Advanced, TownyWands and ProtocolLib.
It worked perfect! Do you have any other plugin that uses Signs and ProtocolLib?
The error you posted above tells something about Chat Packets, what is your ChatPlugin?

**Comment by OscarGLorenz** [comment]
My fault, I tested again adding to my server plugin by plugin and the guilty plugin is ReActions 0.9.9 :
http://dev.bukkit.org/bukkit-plugins/reactions/

**Comment by FastFelix771** [comment]
Does it react to Signs?
I will try to find a way arround this issue, its time for an update anyways ._.

**Comment by OscarGLorenz** [comment]
Yes it does
One of the features of reactions is recognize predefined words in signs to Activate some "ReActions" on click

**Comment by FastFelix771** [comment]
I have updated and tested the plugin a little bit, hopefully it contains the fix you need.
In my tests it worked well with ProtocolLib, Towny, TownyChat, ReActions and some Economy plugin on Spigot 1.8.8 (tested with PaperSpigot, too)
